#!/bin/bash

# Store the ID of focused window
PREVIOUS_WINDOW=$(xdotool getactivewindow)

# Send toggle deafen keybind to Discord
xdotool search --onlyvisible --name "Discord" windowfocus --sync key --clearmodifiers "Control+Shift+D"

# Activate the previous window
xdotool windowfocus "$PREVIOUS_WINDOW"
